# Describes the format for available ADS services

write_data_by_name:
  fields:
    adsvar:
      required: true
      example: ".global_var"
      selector:
        text:
    adstype:
      required: true
      selector:
        select:
          options:
            - "bool"
            - "byte"
            - "date"
            - "dint"
            - "dt"
            - "dword"
            - "int"
            - "lreal"
            - "real"
            - "sint"
            - "string"
            - "time"
            - "tod"
            - "udint"
            - "uint"
            - "usint"
            - "word"
    value:
      required: true
      example: "21.5"
      selector:
        text:
